### ISSUE TITLE
Recommended to rename `wechaty-puppet-0.41.9` branch to `v0.41`

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-whatsapp#119]
`wechaty-puppet-0.41.9` branch maintained by @su-chang would be better to be renamed to `v0.41` so that it can be CI/CD.

Please let me know if we can do it or not.

**Comment by su-chang** [comment]
> `wechaty-puppet-0.41.9` branch maintained by @su-chang would be better to be renamed to `v0.41` so that it can be CI/CD.
> 
> Please let me know if we can do it or not.

Of course, I will do it today.

**Comment by huan** [comment]
That's great, thank you very much!

**Comment by su-chang** [comment]
Now `wechaty-puppet-0.41.9` branch is protected branch, I need @windmemory help to change it's name to `v0.41`.

**Comment by huan** [comment]
I have helped you renamed the name of the below two branches to follow the version pattern:

1. wechaty-puppet-0.41.9 -> v0.41
1. v1.11.57 -> v1.11

And they are all protected branches.

Please feel free to let me know if you have any questions.

**Comment by su-chang** [comment]
Thank you very much.

**Comment by huan** [comment]
You are welcome.

Please also notice that the `version` in the `package.json` has been updated as well to match the branch name.

This will affect the published NPM version to be `0.41` in the following CI/CD actions.
