### ISSUE TITLE
docker方式运行wechaty-whatsapp，遇到如下错误：Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053)，如何解决

### ISSUE THREAD

**Issue by chenzhiqiang0518** [wechaty/wechaty-puppet-whatsapp#398]
![image](https://github.com/wechaty/puppet-whatsapp/assets/40555815/4f000c7f-a2eb-4db7-8323-b820d3e69d8c)

docker命令：
docker run -ti --rm --name wechaty-whatsapp --privileged --network=host -e WECHATY_LOG="verbose" -e WECHATY_PUPPET="wechaty-puppet-whatsapp" -e WECHATY_TOKEN="puppet_padlocal_xxx" -e WECHATY_PUPPET_SERVER_PORT="8091" -p "8091:8091" wechaty/wechaty:latest

**Comment by huan** [comment]
Duplicate & merge to https://github.com/wechaty/docker-getting-started/issues/11
